### ISSUE TITLE
Determine Data Shapes - Closest Store

### ISSUE THREAD

**Issue by monstaro** [track-basket/trackbasket_FE#2]
## Issue
- [ ] Style (non-breaking style code)
- [ ] Testing (add testing to code)
- [ ] Refactor (improvement to the code)
- [ ] New feature (change which adds functionality)
- [X] Chore
## Issue Summary
Front end sending LatLong to BE
BE returning closest store

## Resources 
List any resources used when working on the issue (e.g. links to articles, stackoverflow, etc.)

**Comment by monstaro** [comment]
```
// STORE LOCATION
// FE sends BE string (latLng) to put in endpoint

// what we expect back


"locationId": "62000001",
      "address": {
        "addressLine1": "1331 Speer Blvd",
        "city": "Denver",
        "state": "CO"
      },
      "geolocation": {
        "latLng": "39.7374922,-104.9979695"
      }
```

**Comment by mronauli** [comment]
``` /api/v1/search/location ```
